// ═══════════════════════════════════════════
// data.js — Regiones, comunas y catálogo PHH
// ═══════════════════════════════════════════

const REGIONES_COMUNAS = [
  { codigo: 'XV', nombre: 'Región de Arica y Parinacota',
    comunas: ['Arica','Camarones','General Lagos','Putre'] },
  { codigo: 'I', nombre: 'Región de Tarapacá',
    comunas: ['Alto Hospicio','Camiña','Colchane','Huara','Iquique','Pica','Pozo Almonte'] },
  { codigo: 'II', nombre: 'Región de Antofagasta',
    comunas: ['Antofagasta','Calama','María Elena','Mejillones','Ollagüe','San Pedro de Atacama','Sierra Gorda','Taltal','Tocopilla'] },
  { codigo: 'III', nombre: 'Región de Atacama',
    comunas: ['Alto del Carmen','Caldera','Chañaral','Copiapó','Diego de Almagro','Freirina','Huasco','Tierra Amarilla','Vallenar'] },
  { codigo: 'IV', nombre: 'Región de Coquimbo',
    comunas: ['Andacollo','Canela','Combarbalá','Coquimbo','Illapel','La Higuera','La Serena','Los Vilos','Monte Patria','Ovalle','Paiguano','Punitaqui','Río Hurtado','Salamanca','Vicuña'] },
  { codigo: 'V', nombre: 'Región de Valparaíso',
    comunas: ['Algarrobo','Cabildo','Calera','Calle Larga','Cartagena','Casablanca','Catemu','Concón','El Quisco','El Tabo','Hijuelas','Isla de Pascua','Juan Fernández','La Cruz','La Ligua','Limache','Llaillay','Los Andes','Nogales','Olmué','Panquehue','Papudo','Petorca','Puchuncaví','Putaendo','Quilpué','Quillota','Quintero','Rinconada','San Antonio','San Esteban','San Felipe','Santa María','Santo Domingo','Valparaíso','Villa Alemana','Viña del Mar','Zapallar'] },
  { codigo: 'RM', nombre: 'Región Metropolitana de Santiago',
    comunas: ['Alhué','Buin','Calera de Tango','Cerrillos','Cerro Navia','Colina','Conchalí','Curacaví','El Bosque','El Monte','Estación Central','Huechuraba','Independencia','Isla de Maipo','La Cisterna','La Florida','La Granja','La Pintana','La Reina','Lampa','Las Condes','Lo Barnechea','Lo Espejo','Lo Prado','Macul','Maipú','María Pinto','Melipilla','Ñuñoa','Padre Hurtado','Paine','Pedro Aguirre Cerda','Peñaflor','Peñalolén','Pirque','Providencia','Pudahuel','Puente Alto','Quilicura','Quinta Normal','Recoleta','Renca','San Bernardo','San Joaquín','San José de Maipo','San Miguel','San Pedro','San Ramón','Santiago','Talagante','Tiltil','Vitacura'] },
  { codigo: 'VI', nombre: "Región del Libertador General Bernardo O'Higgins",
    comunas: ['Chépica','Chimbarongo','Codegua','Coinco','Coltauco','Doñihue','Graneros','La Estrella','Las Cabras','Litueche','Lolol','Machalí','Malloa','Marchihue','Mostazal','Nancagua','Navidad','Olivar','Palmilla','Paredones','Peralillo','Peumo','Pichidegua','Pichilemu','Placilla','Pumanque','Quinta de Tilcoco','Rancagua','Rengo','Requínoa','San Fernando','San Vicente','Santa Cruz'] },
  { codigo: 'VII', nombre: 'Región del Maule',
    comunas: ['Cauquenes','Chanco','Colbún','Constitución','Curepto','Curicó','Empedrado','Hualañé','Licantén','Linares','Longaví','Maule','Molina','Parral','Pelarco','Pelluhue','Pencahue','Rauco','Retiro','Río Claro','Romeral','Sagrada Familia','San Clemente','San Javier','San Rafael','Talca','Teno','Vichuquén','Villa Alegre','Yerbas Buenas'] },
  { codigo: 'XVI', nombre: 'Región de Ñuble',
    comunas: ['Bulnes','Chillán','Chillán Viejo','Cobquecura','Coelemu','Coihueco','El Carmen','Ninhue','Ñiquén','Pemuco','Pinto','Portezuelo','Quillón','Quirihue','Ránquil','San Carlos','San Fabián','San Ignacio','San Nicolás','Treguaco','Yungay'] },
  { codigo: 'VIII', nombre: 'Región del Biobío',
    comunas: ['Alto Biobío','Antuco','Arauco','Cabrero','Cañete','Chiguayante','Concepción','Contulmo','Coronel','Curanilahue','Florida','Hualqui','Hualpén','Laja','Lebu','Los Álamos','Los Ángeles','Lota','Mulchén','Nacimiento','Negrete','Penco','Quilaco','Quilleco','San Pedro de la Paz','San Rosendo','Santa Bárbara','Santa Juana','Talcahuano','Tirúa','Tomé','Tucapel','Yumbel'] },
  { codigo: 'IX', nombre: 'Región de La Araucanía',
    comunas: ['Angol','Carahue','Cholchol','Collipulli','Cunco','Curacautín','Curarrehue','Ercilla','Freire','Galvarino','Gorbea','Lautaro','Loncoche','Lonquimay','Los Sauces','Lumaco','Melipeuco','Nueva Imperial','Padre Las Casas','Perquenco','Pitrufquén','Pucón','Purén','Renaico','Saavedra','Temuco','Teodoro Schmidt','Toltén','Traiguén','Victoria','Vilcún','Villarrica'] },
  { codigo: 'XIV', nombre: 'Región de Los Ríos',
    comunas: ['Corral','Futrono','La Unión','Lago Ranco','Lanco','Los Lagos','Máfil','Mariquina','Paillaco','Panguipulli','Río Bueno','Valdivia'] },
  { codigo: 'X', nombre: 'Región de Los Lagos',
    comunas: ['Ancud','Calbuco','Castro','Chaitén','Chonchi','Cochamó','Curaco de Vélez','Dalcahue','Fresia','Frutillar','Futaleufú','Hualaihué','Llanquihue','Los Muermos','Maullín','Osorno','Palena','Puerto Montt','Puerto Octay','Puerto Varas','Puqueldón','Purranque','Puyehue','Queilén','Quemchi','Quínchao','Río Negro','San Juan de la Costa','San Pablo'] },
  { codigo: 'XI', nombre: 'Región de Aysén del General Carlos Ibáñez del Campo',
    comunas: ['Aysén','Chile Chico','Cisnes','Cochrane','Coyhaique','Guaitecas','Lago Verde',"O'Higgins",'Río Ibáñez','Tortel'] },
  { codigo: 'XII', nombre: 'Región de Magallanes y de la Antártica Chilena',
    comunas: ['Antártica','Cabo de Hornos','Laguna Blanca','Natales','Porvenir','Primavera','Punta Arenas','Río Verde','San Gregorio','Timaukel','Torres del Paine'] },
];

// ─────────────────────────────────────────────
// Catálogo de servicios
// ─────────────────────────────────────────────
const CATALOGO_ITEMS = [
  // ── SERV.CONST — Servicios de Construcción ──
  { codigo:'SERV.CONST.001', descripcion:'Demolición tabique estuco / ladrillo (M.O.)',        unidad:'m²', precio:8000,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.002', descripcion:'Demolición tabique yeso-cartón (M.O.)',               unidad:'m²', precio:5500,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.003', descripcion:'Tabique yeso-cartón simple (M.O.)',                   unidad:'m²', precio:35000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.004', descripcion:'Tabique yeso-cartón doble cara (M.O.)',               unidad:'m²', precio:52000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.005', descripcion:'Pintura látex muros y cielo (M.O.)',                  unidad:'m²', precio:8500,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.006', descripcion:'Pintura esmalte puertas y ventanas (M.O.)',           unidad:'m²', precio:12000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.007', descripcion:'Instalación piso flotante laminado (M.O.)',           unidad:'m²', precio:9000,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.008', descripcion:'Instalación cerámico piso o muro (M.O.)',             unidad:'m²', precio:22000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.009', descripcion:'Instalación porcelanato piso o muro (M.O.)',          unidad:'m²', precio:28000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.010', descripcion:'Cielo falso yeso-cartón (M.O.)',                      unidad:'m²', precio:32000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.011', descripcion:'Cielo falso tipo Armstrong (M.O.)',                   unidad:'m²', precio:24000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.012', descripcion:'Instalación puerta interior (M.O.)',                  unidad:'un', precio:55000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.013', descripcion:'Instalación ventana PVC (M.O.)',                      unidad:'un', precio:45000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.014', descripcion:'Instalación ventana aluminio (M.O.)',                 unidad:'un', precio:40000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.015', descripcion:'Cubierta zinc ondulado (M.O.)',                       unidad:'m²', precio:25000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.016', descripcion:'Cubierta teja española (M.O.)',                       unidad:'m²', precio:38000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.017', descripcion:'Impermeabilización de cubierta (M.O.)',               unidad:'m²', precio:18000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.018', descripcion:'Muro de hormigón armado (M.O.)',                      unidad:'m²', precio:85000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.019', descripcion:'Excavación manual',                                   unidad:'m³', precio:45000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.020', descripcion:'Radier hormigón H-15 (M.O.)',                         unidad:'m²', precio:42000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.021', descripcion:'Estuco fino en muros (M.O.)',                         unidad:'m²', precio:14000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.022', descripcion:'Instalación zócalo MDF / madera (M.O.)',              unidad:'ml', precio:8500,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.023', descripcion:'Instalación piso vinílico PVC (M.O.)',                unidad:'m²', precio:7500,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.024', descripcion:'Retiro de escombros con camión',                      unidad:'gl', precio:180000, grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.025', descripcion:'Cambio de cubierta completa (M.O.)',                  unidad:'m²', precio:65000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.026', descripcion:'Limpieza y aseo final de obra',                       unidad:'gl', precio:90000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.027', descripcion:'Instalación revestimiento OSB (M.O.)',                unidad:'m²', precio:20000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.028', descripcion:'Instalación deck madera tratada (M.O.)',              unidad:'m²', precio:45000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.029', descripcion:'Ampliación de ventana / vano (M.O.)',                 unidad:'un', precio:120000, grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.030', descripcion:'Estructura metalcon / steel framing (M.O.)',          unidad:'m²', precio:28000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.031', descripcion:'Instalación revestimiento exterior fibrocemento',     unidad:'m²', precio:32000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.032', descripcion:'Instalación guardapolvo madera o MDF',                unidad:'ml', precio:6500,   grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.033', descripcion:'Nivelación y preparación de terreno',                 unidad:'m²', precio:15000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.034', descripcion:'Instalación malla acma / fierro (M.O.)',              unidad:'m²', precio:18000,  grupo:'SERV.CONST' },
  { codigo:'SERV.CONST.035', descripcion:'Faena de maestro constructor (jornal)',               unidad:'hr', precio:12500,  grupo:'SERV.CONST' },

  // ── SERV.GASF — Servicios de Gasfitería ─────
  { codigo:'SERV.GASF.001', descripcion:'Instalación lavamanos (M.O.)',                         unidad:'un', precio:65000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.002', descripcion:'Instalación WC / inodoro (M.O.)',                      unidad:'un', precio:85000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.003', descripcion:'Instalación ducha / receptáculo (M.O.)',               unidad:'un', precio:75000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.004', descripcion:'Instalación tina / bañera (M.O.)',                     unidad:'un', precio:95000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.005', descripcion:'Instalación lavaplatos (M.O.)',                        unidad:'un', precio:70000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.006', descripcion:'Instalación calefón a gas (M.O.)',                     unidad:'un', precio:110000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.007', descripcion:'Instalación llave de paso general (M.O.)',             unidad:'un', precio:55000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.008', descripcion:'Instalación llave de paso individual (M.O.)',          unidad:'un', precio:35000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.009', descripcion:'Reparación cañería agua fría o caliente (M.O.)',       unidad:'ml', precio:28000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.010', descripcion:'Instalación cañería PVC agua fría (M.O.)',             unidad:'ml', precio:12000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.011', descripcion:'Instalación cañería PPR agua caliente (M.O.)',         unidad:'ml', precio:18000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.012', descripcion:'Desatasco cañería / WC',                               unidad:'un', precio:45000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.013', descripcion:'Instalación mezcladora / termostato (M.O.)',           unidad:'un', precio:85000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.014', descripcion:'Revisión y reparación de fuga de agua',                unidad:'gl', precio:55000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.015', descripcion:'Instalación medidor de agua (M.O.)',                   unidad:'un', precio:95000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.016', descripcion:'Instalación caldera / boiler eléctrico (M.O.)',        unidad:'un', precio:120000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.017', descripcion:'Cambio cañería completo baño (M.O.)',                  unidad:'gl', precio:380000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.018', descripcion:'Red agua fría completa — vivienda (M.O.)',             unidad:'gl', precio:250000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.019', descripcion:'Red agua caliente completa — vivienda (M.O.)',         unidad:'gl', precio:320000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.020', descripcion:'Instalación estanque / cisterna WC (M.O.)',            unidad:'un', precio:55000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.021', descripcion:'Instalación llave jardín / exterior (M.O.)',           unidad:'un', precio:30000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.022', descripcion:'Instalación sello sanitario WC (M.O.)',                unidad:'un', precio:25000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.023', descripcion:'Cambio de válvula / llave completo (M.O.)',            unidad:'un', precio:40000,  grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.024', descripcion:'Instalación sistema de alcantarillado (M.O.)',         unidad:'gl', precio:450000, grupo:'SERV.GASF' },
  { codigo:'SERV.GASF.025', descripcion:'Revisión general instalación gasfitería',              unidad:'gl', precio:65000,  grupo:'SERV.GASF' },
];
