const {PGlite}=require('@electric-sql/pglite');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
process.chdir(path.resolve(__dirname,'..'));
(async()=>{
const db=new PGlite();
const admin='11111111-1111-4111-8111-111111111111', client='22222222-2222-4222-8222-222222222222', member='33333333-3333-4333-8333-333333333333';
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
await db.exec("create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key,email text); create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$; grant usage on schema auth,public to anon,authenticated; grant execute on function auth.uid() to anon,authenticated;");
await db.exec('alter default privileges in schema public grant all on tables to authenticated,anon;');
const base=fs.readFileSync('supabase_schema.sql','utf8');
await db.exec(base.slice(0,base.indexOf('-- PASO 2')));
await db.exec("insert into auth.users values ('"+admin+"','admin@test.local'),('"+client+"','cliente@test.local'),('"+member+"','miembro@test.local'); insert into public.empresas(id,nombre_comercial,aprobada,limite_usuarios) values ('"+a+"','Plataforma',true,3),('"+b+"','Cliente',true,3); insert into public.perfiles(id,empresa_id,rol,es_superadmin) values ('"+admin+"','"+a+"','admin',true),('"+client+"','"+b+"','admin',false),('"+member+"','"+b+"','miembro',false); insert into public.presupuestos(id,empresa_id,data) values ('p1','"+a+"','{}'),('p2','"+b+"','{}');");
await db.exec(fs.readFileSync('supabase/migrations/202610050001_plataforma.sql','utf8'));
async function as(user,role='authenticated'){ await db.exec("reset role; set role "+role+"; select set_config('request.jwt.claim.sub','"+user+"',false);"); }
async function value(sql){return (await db.query(sql)).rows[0].v;}
async function rejects(sql,pattern){await assert.rejects(db.exec(sql),pattern);}
await as(client);
assert.equal(await value("select (public.estado_servicio('"+b+"')->>'operativo')::boolean v"),true);
assert.equal(await value("select count(*)::int v from public.presupuestos"),1);
await rejects("select public.plataforma_cambiar_acceso('"+a+"','autorizada','ataque')",/No autorizado/);
await rejects("update public.empresas set estado_acceso='autorizada' where id='"+b+"'",/permission denied/);
await rejects("update public.perfiles set es_superadmin=true where id='"+client+"'",/permission denied/);
await as(admin);
await db.exec("select public.plataforma_configurar_suscripcion('"+b+"','Mensual',20000,(now() at time zone 'America/Santiago')::date,0,false)");
await as(client);
assert.equal(await value("select (public.estado_servicio('"+b+"')->>'operativo')::boolean v"),false);
assert.equal(await value("select count(*)::int v from public.presupuestos"),0);
await rejects("insert into public.presupuestos values ('p3','"+b+"','{}',now())",/row-level security/);
await rejects("insert into public.pagos_suscripcion(id) values(gen_random_uuid())",/permission denied/);
await as(admin);
const date=await value("select (now() at time zone 'America/Santiago')::date::text v");
const pid='44444444-4444-4444-8444-444444444444';
const pay="select public.plataforma_registrar_pago('"+pid+"','"+b+"','"+date+"',20000,'BANCO-001','"+date+"')";
await db.exec(pay); await db.exec(pay);
assert.equal(await value("select periodos_pagados v from public.suscripciones where empresa_id='"+b+"'"),1);
assert.equal(await value("select count(*)::int v from public.pagos_suscripcion"),1);
await rejects(pay.replace('20000','19999'),/otros datos/);
await rejects(pay.replace(pid,'55555555-5555-4555-8555-555555555555'),/período cambió/);
await rejects("select public.plataforma_configurar_suscripcion('"+b+"','Mensual',20000,'2025-01-01',5,false)",/inicio no se cambia/);
await rejects("select public.set_limite_usuarios('"+b+"',1)",/cupo debe cubrir/);
await rejects("select public.plataforma_cambiar_acceso('"+a+"','bloqueada','Prueba bloqueo')",/administradores de plataforma/);
await db.exec("select public.plataforma_cambiar_acceso('"+b+"','bloqueada','Bloqueo administrativo')");
await as(client);
assert.equal(await value("select (public.estado_servicio('"+b+"')->>'operativo')::boolean v"),false);
assert.equal(await value("select count(*)::int v from public.pagos_suscripcion"),1);
await as(member);
assert.equal(await value("select count(*)::int v from public.pagos_suscripcion"),0);
assert.equal(await value("select count(*)::int v from public.suscripciones"),0);
await as(admin);
await db.exec("select public.plataforma_cambiar_acceso('"+b+"','autorizada','Reactivar cuenta')");
await as(client);
assert.equal(await value("select count(*)::int v from public.presupuestos"),1);
assert.equal(await value("select public.fecha_ciclo('2025-01-31',1)::text v"),'2025-02-28');
assert.equal(await value("select public.fecha_ciclo('2025-01-31',2)::text v"),'2025-03-31');
await as(client);
await db.exec("update public.presupuestos set data=jsonb_build_object('ordenesTrabajo',jsonb_build_array(jsonb_build_object('id','ot-b'))) where id='p2'");
const publish="select public.publicar_ot('ot-b','OT-1','P-2','Cliente','CLP',0,'Ana',null,null,null,null,'[]',0,0,0,0,0,true,0,0,0)";
await db.exec(publish);
await as(admin);
await rejects(publish,/Guarda la orden/);
await as(client);
await db.exec(publish.replace("'Ana'","'Ana actualizada'"));
await as(admin);
await db.exec("select public.plataforma_cambiar_acceso('"+b+"','suspendida','Prueba de suspensión')");
await as(client);
await rejects(publish,/Sin acceso/);
await as('', 'anon');
await db.exec("select public.firmar_ot_publica('ot-b','firma-prueba',null)");
assert.equal(await value("select estado v from public.obtener_ot_publica('ot-b')"),'firmada');

await as('', 'anon');
assert.equal(await value("select has_function_privilege('anon','public.plataforma_registrar_pago(uuid,uuid,date,integer,text,date)','EXECUTE') v"),false);
assert.equal(await value("select has_function_privilege('anon','public.publicar_ot(text,text,text,text,text,integer,text,text,text,text,text,jsonb,numeric,numeric,numeric,numeric,numeric,boolean,numeric,numeric,numeric)','EXECUTE') v"),false);
await as(admin);
await db.exec("select public.plataforma_cambiar_acceso('"+b+"','archivada','Baja solicitada')");
await rejects("select public.plataforma_eliminar_empresa('"+b+"','Cliente')",/documentos o pagos/);
await db.exec("reset role");
const c='cccccccc-cccc-4ccc-8ccc-cccccccccccc',newuser='66666666-6666-4666-8666-666666666666';
await db.exec("insert into auth.users values('"+newuser+"','nuevo@test.local'); insert into public.empresas(id,nombre_comercial,aprobada,estado_acceso) values('"+c+"','Nueva',true,'autorizada'); insert into public.perfiles(id,empresa_id,rol) values('"+newuser+"','"+c+"','admin')");
await as(newuser);
assert.equal(await value("select (public.estado_servicio('"+c+"')->>'operativo')::boolean v"),false);
await rejects("select public.plataforma_eliminar_empresa('"+c+"','Nueva')",/No autorizado/);
await as(admin);
await db.exec("select public.plataforma_cambiar_acceso('"+c+"','archivada','Baja de prueba')");
await rejects("select public.plataforma_eliminar_empresa('"+c+"','nombre incorrecto')",/confirma su nombre/);
await db.exec("select public.plataforma_eliminar_empresa('"+c+"','Nueva')");
assert.equal(await value("select count(*)::int v from public.empresas where id='"+c+"'"),0);
assert.equal(await value("select count(*)::int v from public.plataforma_historial where accion='eliminacion' and empresa_id is null"),1);

await as(newuser);
await rejects("select public.estado_servicio('"+b+"')",/No autorizado/);
await db.close();
console.log('Migración ejecutada en PostgreSQL temporal: permisos, aislamiento, deuda, pagos idempotentes, cupos y bloqueo correctos.');
})().catch(e=>{console.error(e.message);process.exit(1);});
