const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
const html=fs.readFileSync('index.html','utf8');
for (const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)) new Function(m[1]);
for (const file of ['app.js','data.js','platform.js','proyectos.js']) new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'IDs HTML duplicados');
const context=vm.createContext({document:{addEventListener(){}},Intl,Date,console});
vm.runInContext(fs.readFileSync('platform.js','utf8')+'\nglobalThis.helpers=Plataforma.test;',context);
const {fechaCiclo,resumen,h}=context.helpers;
assert.equal(fechaCiclo('2025-01-31',1),'2025-02-28');
assert.equal(fechaCiclo('2025-01-31',2),'2025-03-31');
assert.equal(fechaCiclo('2024-01-31',1),'2024-02-29');
assert.equal(fechaCiclo('2025-12-31',2),'2026-02-28');
const e={estado_acceso:'autorizada',aprobada:true,acceso_transitorio:true};
const s={inicio:'2026-01-31',periodos_pagados:1,dias_gracia:5,cancelada:false};
assert.equal(resumen(e,s,'2026-02-27').estado_pago,'al_dia');
assert.equal(resumen(e,s,'2026-02-28').estado_pago,'en_gracia');
assert.equal(resumen(e,s,'2026-03-04').operativo,true);
assert.equal(resumen(e,s,'2026-03-05').operativo,false);
assert.equal(resumen({...e,estado_acceso:'bloqueada'},s,'2026-02-10').operativo,false);
assert.equal(resumen(e,{...s,cancelada:true},'2026-02-27').operativo,true);
assert.equal(resumen(e,{...s,cancelada:true},'2026-02-28').operativo,false);
assert.equal(resumen(e,s,'2026-01-30').operativo,false);
assert.equal(resumen(e,null,'2026-12-31').operativo,true);
assert.equal(resumen({...e,acceso_transitorio:false},null,'2026-12-31').operativo,false);
assert.equal(h('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');
// Cuenta de cortesía: opera sin pagos ni vencimiento mientras esté autorizada y no cancelada.
const c={inicio:'2026-10-10',periodos_pagados:0,dias_gracia:5,cancelada:false,cortesia:true,monto_mensual:0};
assert.equal(resumen(e,c,'2026-10-10').estado_pago,'cortesia');
assert.equal(resumen(e,c,'2027-12-31').operativo,true);
assert.equal(resumen(e,c,'2027-12-31').vencimiento,null);
assert.equal(resumen(e,c,'2026-10-09').operativo,false);
assert.equal(resumen(e,{...c,cancelada:true},'2026-10-10').operativo,false);
assert.equal(resumen({...e,estado_acceso:'suspendida'},c,'2026-10-10').operativo,false);
// «Autorizada» con la suscripción cancelada y sin pagos NO opera, y la pantalla dice por qué (caso del 10-10-2026).
const cancelada=resumen(e,{inicio:'2026-10-10',periodos_pagados:0,dias_gracia:5,cancelada:true},'2026-10-10');
assert.equal(cancelada.operativo,false);
assert.match(cancelada.motivo,/cancelada y no tiene ningún período pagado/);
assert.equal(resumen(e,s,'2026-03-04').motivo,'');
assert.match(resumen(e,s,'2026-03-05').motivo,/venció el 28\/02\/2026/);
assert.match(resumen({...e,estado_acceso:'bloqueada'},s,'2026-02-10').motivo,/bloqueada/);
assert.match(resumen({...e,acceso_transitorio:false},null,'2026-12-31').motivo,/plan o marcarla como cortesía/);
console.log('ALL SCRIPTS VALID · HTML y comprobaciones de fechas, acceso, cortesía y escape correctas');
