const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
const html=fs.readFileSync('index.html','utf8');
for (const m of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g)) new Function(m[1]);
for (const file of ['app.js','data.js','platform.js']) new vm.Script(fs.readFileSync(file,'utf8'),{filename:file});
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'IDs HTML duplicados');
const context=vm.createContext({document:{addEventListener(){}},Intl,Date,console});
vm.runInContext(fs.readFileSync('platform.js','utf8')+'\nglobalThis.helpers=Plataforma.test;',context);
const {fechaCiclo,resumen,h}=context.helpers;
assert.equal(fechaCiclo('2025-01-31',1),'2025-02-28');
assert.equal(fechaCiclo('2025-01-31',2),'2025-03-31');
assert.equal(fechaCiclo('2024-01-31',1),'2024-02-29');
assert.equal(fechaCiclo('2025-12-31',2),'2026-02-28');
const e={estado_acceso:'autorizada',aprobada:true,acceso_transitorio:true};
const s={inicio:'2026-01-31',periodos_pagados:1,dias_gracia:5,cancelada:false};
assert.equal(resumen(e,s,'2026-02-27').estado_pago,'al_dia');
assert.equal(resumen(e,s,'2026-02-28').estado_pago,'en_gracia');
assert.equal(resumen(e,s,'2026-03-04').operativo,true);
assert.equal(resumen(e,s,'2026-03-05').operativo,false);
assert.equal(resumen({...e,estado_acceso:'bloqueada'},s,'2026-02-10').operativo,false);
assert.equal(resumen(e,{...s,cancelada:true},'2026-02-27').operativo,true);
assert.equal(resumen(e,{...s,cancelada:true},'2026-02-28').operativo,false);
assert.equal(resumen(e,s,'2026-01-30').operativo,false);
assert.equal(resumen(e,null,'2026-12-31').operativo,true);
assert.equal(resumen({...e,acceso_transitorio:false},null,'2026-12-31').operativo,false);
assert.equal(h('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');
console.log('ALL SCRIPTS VALID · HTML y comprobaciones de fechas, acceso y escape correctas');
